# Generated by Django 2.2 on 2020-10-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='show',
            name='release',
            field=models.CharField(max_length=24),
        ),
    ]
