# Generated by Django 2.2 on 2020-09-23 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dragons',
            new_name='Dragon',
        ),
    ]
